---
ansible_python_interpreter: /usr/bin/python3
ansible_user: devops

# role
devops_user: devops
devops_public_key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/linode.pub') }}"

# github account
ghcr_username: "tysker"
ghcr_token: "{{ lookup('env', 'GHCR_TOKEN') }}"

# node-exporter
node_exporter_image: "prom/node-exporter:v1.8.1"
node_exporter_port: 9100
...

