---
app_image: "ghcr.io/tysker/cloud_devops_app:0950da9"
app_container_name: "cloud-devops-app"
app_container_port: 5000
app_public_port: 5000

# caddy
caddy_config_dir: "/opt/caddy/config"
caddy_data_dir: "/opt/caddy/data"
caddy_image: "caddy:2.10.0-alpine"
...
