ansible_python_interpreter: /usr/bin/python3

# role
devops_user: devops
devops_public_key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/linode.pub') }}"

# github account
ghcr_username: "tysker"
ghcr_token: "{{ lookup('env', 'GHCR_TOKEN') }}"
