ansible_python_interpreter: /usr/bin/python3
devops_user: devops
devops_public_key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/linode.pub') }}"
app_image: "ghcr.io/tysker/cloud_devops_app:77ecd38"
app_container_name: "cloud-devops-app"
app_container_port: 5000
app_public_port: 80
ghcr_username: "tysker"
ghcr_token: "{{ lookup('env', 'GHCR_TOKEN') }}"
