prometheus_image: "prom/prometheus:v2.52.0"
prometheus_port: 9090
prometheus_config_dir: "/opt/prometheus"
prometheus_data_dir: "/opt/prometheus/data"
node_exporter_image: "prom/node-exporter:v1.8.1"
node_exporter_port: 9100
